version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
  localstack:
    image: localstack/localstack      
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,s3
      - SQS_PROVIDER=elasticmq
      - EAGER_SERVICE_LOADING=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  